name: GitHub-Profile-3D-Contrib

on:
  schedule: # 09:00 BST == 1:00 UTC
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name zys8119
          git config user.email 770959294@qq.com
          git add -A .
          git commit -m "generated"
          git push
